### ISSUE TITLE
Getting web page does not exist error (Android)

### ISSUE THREAD

**Issue by imariman** [timtraversy/new_version#10]
Today, my app's new version is published on Google Play Store. I had an old version of my app installed in my device. When I started the app, it asked me to update the app. But when I click the link, I got "web page does not exists" error.

intent://play.app.goo.gl/?link=https://play.google.com/store/apps/details?id%3Dcom.swoddy.swoddy_app#Intent;package=com.google.android.gms;scheme=https;S.browsefallback_url=https://play.google.com/store/apps/details%3Fid%3Dcom.swoddy.swoddy_app;end;

![120661238_335267921113773_6334398577225980652_n](https://user-images.githubusercontent.com/34774588/94989922-d7d5d500-0580-11eb-841d-f0ac9bc045e8.jpg)

I have the latest version of new_version package (v0.0.5).

**Comment by imariman** [comment]
No, I don't pass a custom androidId. Actually the url is correct, in my case it is "https://play.google.com/store/apps/details?id=com.swoddy.swoddy_app". await launch(appStoreLink) works fine; but await launch(appStorelink, forceWebView: true) somehow doesn't work. Although I am passing the correct url, if I set forceWebView true, it doesn't work.

**Comment by timtraversy** [comment]
Hm I can't really remember why I decided to force web view. I could just remove that parameter.

**Comment by benjastudio** [comment]
Hi, I faced the same problem, and indeed thae you @timtraversy mentionned fixed the issue for me: https://github.com/benjastudio/new_version/commit/d9647fef85df0f4e26ee47ee52dfe0284155fdc7

It may be nice to add a parameter to force or not the webview (or remove it completely).

**Comment by timtraversy** [comment]
Ok I removed this parameter in the last release, so closing this for now.
