### ISSUE TITLE
Confirm that the APP has been updated

### ISSUE THREAD

**Issue by rodrigonepomuceno** [timtraversy/new_version#100]
Is there any way to wait for it to update and then continue. For example, I close the modal, but if it didn't update, or went to the store, it gave an error and returned to close the App or return some warning that it didn't update?

**Comment by timtraversy** [comment]
Well updating the app will kill it and restart it, so if they keep using the app after seeing the dialog, they haven't updated the app. There is an option to prevent the user from dismissing the dialog.
