### ISSUE TITLE
Can't find an app in the App Store with id also playstore

### ISSUE THREAD

**Issue by Irfadg** [timtraversy/new_version#103]
i am getting this message "Can't find an app in the App Store with the id: com.xxxxx.xxxxx" even if my app is test on both appstore and playstore.

**Comment by timtraversy** [comment]
What do you mean by "test'?

**Comment by Irfadg** [comment]
internal testing in google play .
testflight in ios

**Comment by timtraversy** [comment]
Yeah that won't work. The plugin queries the public Play Store and the iTunes API for the real App Store. But it will work once you've published.
