### ISSUE TITLE
Forcing Minimum App Version in Internal Testing / TestFlight Stage

### ISSUE THREAD

**Issue by serpentarius-hollow** [timtraversy/new_version#106]
Hi! I was wondering can we try to force the minimum app version while our app is still in Internal Testing/TestFlight stage? Thank you.

**Comment by timtraversy** [comment]
Yes.
https://github.com/timtraversy/new_version/blob/a71a9b8428cb1fd5fe809806f72356d4e1c41bb4/lib/new_version.dart#L79-L82
