### ISSUE TITLE
 Bad state: No element

### ISSUE THREAD

**Issue by s2yed** [timtraversy/new_version#108]
tter (21285): Bad state: No element
I/flutter (21285): 
I/flutter (21285): #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
I/flutter (21285): #1      NewVersion._getAndroidStoreVersion (package:new_version/new_version.dart:152:51)
I/flutter (21285): <asynchronous suspension>

**Comment by timtraversy** [comment]
Duplicate #107
