### ISSUE TITLE
 Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by codendtech** [timtraversy/new_version#109]
E/flutter (17395): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: No element
E/flutter (17395): #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
E/flutter (17395): #1      NewVersion._getAndroidStoreVersion
package:new_version/new_version.dart:157
E/flutter (17395): <asynchronous suspension>
E/flutter (17395): #2      HomeScreenViewModel._appUpdateCheck
package:grand_ecom/view_model/home_screen_viewmodel.dart:159
E/flutter (17395): <asynchronous suspension>
E/flutter (17395): #3      HomeScreenViewModel.getHomeData
package:grand_ecom/view_model/home_screen_viewmodel.dart:117
E/flutter (17395): <asynchronous suspension>
E/flutter (17395):

**Comment by lkrjangid1** [comment]
Same Here

```
E/flutter (23246): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: No element
E/flutter (23246): #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
E/flutter (23246): #1      NewVersion._getAndroidStoreVersion
package:new_version/new_version.dart:157
E/flutter (23246): <asynchronous suspension>
```

**Comment by azharbinanwar** [comment]
I'm also getting this issue. 😞

**Comment by timtraversy** [comment]
Duplicate #107
