### ISSUE TITLE
Error in iOS - Cannot find package name on API.

### ISSUE THREAD

**Issue by yakeer** [timtraversy/new_version#18]
Hey.
Thanks for your nice plugin.

I have a weird issue,
The package does not recognize that my app exists at all.

I'm not sure if it's your issue, or something wrong with the App Store,
But the api you're connecting to returning 0 results for my package name.

Is there should be any special settings for the API to recognize the application?

It's published in App Store (only for certain countries).

Will appreciate some help in here regarding this.

**Comment by timtraversy** [comment]
Would you mind sharing the bundle ID of your app?

**Comment by yakeer** [comment]
> Would you mind sharing the bundle ID of your app?

com.capitan.zoos

**Comment by timtraversy** [comment]
Yeah https://itunes.apple.com/lookup?bundleId=com.capitan.zoos is returning 0 results as you reported. Could you send me the link to the App Store listing?

**Comment by timtraversy** [comment]
And what countries is it listed in? This could coincide with https://github.com/timtraversy/new_version/pull/16

**Comment by timtraversy** [comment]
When you have a second, could you let me know if your app is on the Android play store? I want to see if this works similarly for the play store.

**Comment by yakeer** [comment]
It's listed in Israel only (both Play Store and App Store).
Link for Play Store:
https://play.google.com/store/apps/details?id=com.capitan.Zoos

Link for App Store:
https://apps.apple.com/il/app/zoos/id1536266307?l=iw
