### ISSUE TITLE
Test the feature

### ISSUE THREAD

**Issue by BartusZak** [timtraversy/new_version#20]
I want to be able to test the feature without changing the version of the app. How can I do it?

```dart
NewVersion(context: context).showAlertIfNecessary();
```

Idea:
- Add `debug: true` param to `showAlertIfNecessary` 

```dart
NewVersion(context: context).showAlertIfNecessary(debug: true);
```

**Comment by timtraversy** [comment]
What would happen if you passed `debug: true` to that function?

If you want to mock behavior, you might just want to use the `newVersion.getVersionStatus()` and use the results differently in tests than in production.

**Comment by timtraversy** [comment]
I'm going to close this since its pretty old, but I'll reopen it if you still want the feature.

**Comment by BartusZak** [comment]
@timtraversy 

I'm working on app which is in `Internal Testing` phase and plugin shows `Can't find an app in the Play Store with the id:`. 

How can I test it?

```
I/flutter (17319): Can't find an app in the Play Store with the id: APP_ID
E/flutter (17319): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value

```

```dart
  @override
  void initState() {
    init();
    super.initState();
  }

  init() async {
    final newVersion = NewVersion();
    newVersion.showAlertIfNecessary(context: context);
    final status = await newVersion.getVersionStatus();
    print(status!.canUpdate); 
    print(status.localVersion); 
    print(status.storeVersion); 
    print(status
        .appStoreLink); 
  }
```
