### ISSUE TITLE
Let canUpdate variable be consistent with beta and production releases on store 

### ISSUE THREAD

**Issue by gehad-ahmed-mohamed** [timtraversy/new_version#22]
Let the returned storeVersion value be as the same release of the localVersion
I mean if the local release is beta then return the storeVersion of last beta release not production release

**Comment by timtraversy** [comment]
Could you clarify this issue a bit more? 

This plugin checks if the version in the store with the same bundle ID/app id has a more recent version.

The app stores don't allow there to be more than one active, production release of an app as far as I know.

Are you referring to TestFlight, or Google Play testing tracks?

**Comment by gehad-ahmed-mohamed** [comment]
@timtraversy  now on the Google Play I have two releases on for beta and one for production .. When I released the beta version which is higher than production .. canUpdate became true .. which is not correct .

So my suggestion that canUpdate be true only if the storeVersion is higher than localVersion ... 
I mean this line isn't accurate 
`versionStatus.canUpdate = versionStatus.storeVersion != versionStatus.localVersion;`

**Comment by timtraversy** [comment]
https://support.google.com/googleplay/android-developer/answer/9845334?hl=en

Are you running an open test, so that your beta app appears in the App Store for some users? Even if that's the case, I'm not sure if you can do a Play Store lookup for test versions.

**Comment by timtraversy** [comment]
Hello - any update on this? Still trying to understand how you imagine this working.

**Comment by gehad-ahmed-mohamed** [comment]
@timtraversy I just want if the user downloaded a release that is bigger than the production release then don't show the message... This will ensure that if the beta release is more recent than the production then the message doesn't annoy him as he already has the updated release...
I suggest to parse the local and the store versions and compare if the local is bigger than the store then let `canUpdate` be false else set it to be true

**Comment by timtraversy** [comment]
Ohh I understand you. You want it to check that the local version is higher, not just equal. That makes sense to me 👍🏼

**Comment by timtraversy** [comment]
Closed by #25
