### ISSUE TITLE
iOS version Issue

### ISSUE THREAD

**Issue by iscojin** [timtraversy/new_version#24]
Hello, guys!
I have an issue with this package for ios.
I have submitted new version ios to the app store and approved.
But still get old version for ios store version.

Who can guide me how to solve this issue?
It is very important thing for me. Cuz I should make our customers force upgrade to new version.

Thanks

**Comment by timtraversy** [comment]
Hello,

I just released a new version of the package, 0.0.7. What version are you currently using?

Tim

**Comment by iscojin** [comment]
Hello,
I was using 0.0.6.
What is the issue with this version for ios?

**Comment by timtraversy** [comment]
Just collecting information. Would you mind sharing your bundle ID?

Was it approved recently? Sometimes it can take time to show up in the App Store after being approved.

**Comment by timtraversy** [comment]
Hello - any update on this?

**Comment by timtraversy** [comment]
Let me know if you can still reproduce this with the new versions.
