### ISSUE TITLE
store version = Varies with device

### ISSUE THREAD

**Issue by HryhoriiZiahun** [timtraversy/new_version#27]
Hello!

new_version: ^0.2.0

My app now in google play alpha
and when I try your library
I get

store version = Varies with device

![image](https://user-images.githubusercontent.com/11783099/114282213-66775300-99f7-11eb-8865-362ff322c3ed.png)

**Comment by HryhoriiZiahun** [comment]
also for android we have really nice way to do this
https://developer.android.com/guide/playcore/in-app-updates
it will be great do native for flutter

**Comment by HryhoriiZiahun** [comment]
and, if someone looks in to do it in correct way
android https://pub.dev/packages/in_app_update
ios  https://pub.dev/packages/upgrader

**Comment by timtraversy** [comment]
Thanks for opening this. I don't plan on adding support for that Android library at the moment, especially since it looks like it is already implemented in another package.
