### ISSUE TITLE
TestFlight (IOS) and Internal ou Closed Test (Google)

### ISSUE THREAD

**Issue by giulianojordao** [timtraversy/new_version#28]
Is there a way to use your library to validate new versions for internal test or testflight cases? This for an app that is not yet available to the general public?

**Comment by abdulrojak288** [comment]
this is a good question, I also want to know the answer

**Comment by timtraversy** [comment]
Hello!

I believe this package supports that behavior: https://github.com/feilfeilundfeil/flutter_in_app_update

But for now, this package just queries the public Play store, so it can only check public apps.
