### ISSUE TITLE
canUpdate logic

### ISSUE THREAD

**Issue by pmagnuson** [timtraversy/new_version#30]
I ran into a case where the new app version is 1.10.1 and the store version is 1.9.4.  In this case the comparison logic fails, and reports that an update is available.   

After a couple of iterations, I settled on the following code for the comparison.  There is probably a better way.  

```dart
bool get canUpdate {
    final localFields = localVersion.split('.');
    final storeFields = storeVersion.split('.');
    String localPad = '';
    String storePad = '';
    for (int i = 0; i < storeFields.length; i++) {
      localPad = localPad + localFields[i].padLeft(3, '0');
      storePad = storePad + storeFields[i].padLeft(3, '0');
    }
    if (localPad.compareTo(storePad) < 0)
      return true;
    else
      return false;
  }
```

**Comment by swarupbhanjachowdhury** [comment]
@pmagnuson can you create a pull request? so we can also take the benefits officially

**Comment by timtraversy** [comment]
Closed with PR.
