### ISSUE TITLE
Error when trying the sample code

### ISSUE THREAD

**Issue by KeithBacalso** [timtraversy/new_version#31]
When I followed the example code:  
` @override
  void initState() {
    super.initState();

    // Implementation is here
    final newVersion = NewVersion(
      iOSId: 'com.google.Vespa',
      androidId: 'com.google.android.apps.cloudconsole',    // I used my own Id here I just copied your sample code..
    );
    newVersion.showAlertIfNecessary(context: context);
  }

it will give error like that in the image.. but I only just followed the sample code...
![Screen Shot 2021-05-12 at 10 39 35 AM](https://user-images.githubusercontent.com/49628565/117910423-7d6ad700-b30e-11eb-8668-db69f74baa65.png)

**Comment by timtraversy** [comment]
Hi - What version of Flutter are you using?
