### ISSUE TITLE
not able to get local version IOS 

### ISSUE THREAD

**Issue by PhanithNoch** [timtraversy/new_version#41]
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      NewVersion._getiOSStoreVersion (package:new_version/new_version.dart:126:39)
<asynchronous suspension>
#2      _HomeScreenState._checkVersion (package:alert_update_version/main.dart:47:20)
<asynchronous suspension>

**Comment by timtraversy** [comment]
Could you provide your bundle ID? The example app is running for me, but the API call could be failing for your app.

**Comment by PhanithNoch** [comment]
this is my bundle id : reanit.course.app.reanit

**Comment by PhanithNoch** [comment]
I also tried with an example project that I tested with Android but it's not working too 

Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
I/flutter_versio( 5602): Not late-enabling -Xcheck:jni (already on)
I/flutter_versio( 5602): Unquickening 12 vdex files!
W/flutter_versio( 5602): Unexpected CPU variant for X86 using defaults: x86
W/flutter_version( 5602): type=1400 audit(0.0:1309): avc: denied { read } for name="max_map_count" dev="proc" ino=718527 scontext=u:r:untrusted_app:s0:c163,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=com.example.flutter_version
W/flutter_versio( 5602): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/flutter_versio( 5602): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_versio( 5602): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/flutter_versio( 5602): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
Debug service listening on ws://127.0.0.1:57826/TKtIY7RTHDU=/ws
Syncing files to device sdk gphone x86...
I/flutter ( 5602): Can't find an app in the Play Store with the id: com.example.flutter_version
E/flutter ( 5602): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 5602): #0      _MyHomePageState._checkVersion (package:flutter_version/main.dart:71:28)
E/flutter ( 5602): <asynchronous suspension>
E/flutter ( 5602):

**Comment by timtraversy** [comment]
Could you clarify what you're trying to accomplish? You might have the wrong idea about how the plugin works. You need to have uploaded your app to the Play Store or App Store first. Then the plugin compares the store version with the locally installed version of the app. 

`reanit.course.app.reanit` doesn't seem to exist on the App Store. And if you use a made up ID like `com.example.flutter_version`, you will get the error you see in that log: 

```
Can't find an app in the Play Store with the id: com.example.flutter_version
```

**Comment by PhanithNoch** [comment]
oh I got it thank you sir
