### ISSUE TITLE
The Whole Package isnt working 

### ISSUE THREAD

**Issue by AdetoyeseMatthew** [timtraversy/new_version#42]
The Whole Example Code isn't working for me

**Comment by AdetoyeseMatthew** [comment]
![Screenshot (106)](https://user-images.githubusercontent.com/34428244/123559005-6fbfc280-d791-11eb-8c9c-9c53ac559503.png)

**Comment by AdetoyeseMatthew** [comment]
Kindly Assist me

**Comment by timtraversy** [comment]
Interesting - it looks like the example code is trying to run an old version of the plug-in. Could you try running `flutter pub get` in the example package to make sure the dependencies are up to date?
