### ISSUE TITLE
Exception on Android when a page doesn't have "what's new" section

### ISSUE THREAD

**Issue by caseyryan** [timtraversy/new_version#45]
Hi,
there is a serious bug in current null-safe version of the plugin
my pull request fixes it 
https://github.com/timtraversy/new_version/pull/44 
The description is inside

**Comment by timtraversy** [comment]
Thank you for reporting this. I'll be able to look at it tonight. Your PR has a few formatting changes that I'd like to revert, but thanks for getting the ball rolling!

**Comment by timtraversy** [comment]
Closed with: https://github.com/timtraversy/new_version/commit/bfbec6c37b1d76a1a720df3c7d5cc68d912e5136
