### ISSUE TITLE
Customize the Popup dialog ?

### ISSUE THREAD

**Issue by GitGud31** [timtraversy/new_version#46]
I dont seem to find a way to customize the buttons or their style. It'd be nice to give more flexibility on this.

**Comment by timtraversy** [comment]
This plugin provides a basic dialog that you can customize the title, content text, and button text of. If you need any more customization than that, you should just display your own dialog after fetching the status, like in the example code.

```
final status = await newVersion.getVersionStatus();
showDialog(
      // Your custom dialog here
);
```

**Comment by timtraversy** [comment]
I don't plan on adding more popup customization, so I am going to close this. You can use the solution posted above if you want to do something different with the version status.
