### ISSUE TITLE
Exception not checked

### ISSUE THREAD

**Issue by francisnnumbi** [timtraversy/new_version#48]
I have currently tested the lib. but you did not provide exception checker on these two methods :

- _getiOSStoreVersion()
- _getAndroidStoreVersion()

I would have branched the changes I did on my forked project, but I'm not able !
Just adding try...catch to returned values:

FOR IOS: _getiOSStoreVersion()
`try {
      return VersionStatus._(
        localVersion: packageInfo.version,
        storeVersion: jsonObj['results'][0]['version'],
        appStoreLink: jsonObj['results'][0]['trackViewUrl'],
        releaseNotes: jsonObj['results'][0]['releaseNotes'],
      );
    } catch (exc) {
      return null;
    }`

FOR ANDROID: _getAndroidStoreVersion()
`  try {
      return VersionStatus._(
        localVersion: packageInfo.version,
        storeVersion: storeVersion,
        appStoreLink: uri.toString(),
        releaseNotes: releaseNotes,
      );
    } catch (exc) {
      return null;
    }`

**Comment by timtraversy** [comment]
Thanks for reporting this. Did you experience a crash, or do you just want to add extra safeguards?

**Comment by francisnnumbi** [comment]
I experienced a crush. I don't have any app on appstore. So, i just put a imaginary value. It crushed. i checked your source code. I saw where it was crushing. I had to wrap it into try...catch.

**Comment by francisnnumbi** [comment]
In fact, it is better to wrap from where you fetch data from the server.

**Comment by timtraversy** [comment]
Going to close this in favor of #50
