### ISSUE TITLE
Error when calling showUpdateDialog in MaterialApp

### ISSUE THREAD

**Issue by rohitb4** [timtraversy/new_version#49]
E/flutter (24494): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter (24494): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.

**Comment by psdike** [comment]
Send your code to check update

**Comment by timtraversy** [comment]
If you google `setState() or markNeedsBuild() called during build` you will find a bunch of people hitting that same error in their projects. You may just need to adjust the timing of when you call for an update and show the dialog. But, this is a general Flutter issue, so I'm going to close it here.
