### ISSUE TITLE
Exception is thrown when app is not in the app store

### ISSUE THREAD

**Issue by michpolicht** [timtraversy/new_version#50]
When the app is not in the app store an exception is thrown during getVersionStatus():

> RangeError (index): Invalid value: Valid value range is empty: 0)

![obraz](https://user-images.githubusercontent.com/2004343/125450692-61c63ef2-110f-4896-9e68-976b5f5dd417.png)

![obraz](https://user-images.githubusercontent.com/2004343/125450547-ff0cb872-a0b8-46f5-ba7e-a6589811bc3d.png)

On Android function works just fine returning null version status and notifying that version status could not be retrieved with debug print.

**Comment by timtraversy** [comment]
Could I ask what your bundle ID is? The status code shouldn't be 200 if the app doesn't exist in the app store.

**Comment by timtraversy** [comment]
Fixed in `2.2.3`
