### ISSUE TITLE
While using showUpdateDialog the action button position is opposite to showAlertIfNecessary actions

### ISSUE THREAD

**Issue by tehsunnliu** [timtraversy/new_version#52]
Hi, when I call `showAlertIfNecessary` function the alertDialog shows "Maybe Later" and "Update" actions. Please note the sequence.
And when I call `showUpdateDialog` the alertDialog shows "Update" and "Maybe Later", here the sequence of the actions don't match. 
For now, I've just changed the sequence at which the actions are added to the actions array.

**Comment by timtraversy** [comment]
Hm, it's hard to see how that is possible. `showAlertIfNecessary` just calls  `showUpdateDialog` after getting the version status. Could you share screenshots?

**Comment by tehsunnliu** [comment]
Hi, so sorry! my bad. I miss interpreted it with the documentation's image. In the doc image, the "Update" button appears first and on the app, it appears later. `showAlertIfNecessary` and `showUpdateDialog` displays the same sequence, the issue is not with the plugin. 
Sorry for opening the wrong issue.

![805cd334-1498-4347-9e49-752871cc8a68](https://user-images.githubusercontent.com/15224865/126603725-a4622b4a-c9c6-49f6-b68b-c7cd1377b4c4.jpeg)
![f91f9bed-8fa1-41ae-9fd7-73018baa7c99](https://user-images.githubusercontent.com/15224865/126603729-2b903745-bd60-467d-ab04-5091c7a07ad0.jpeg)

**Comment by timtraversy** [comment]
Ok good to hear :) thanks for the report.
