### ISSUE TITLE
update button 

### ISSUE THREAD

**Issue by engajerest** [timtraversy/new_version#53]
update button for our application is not showing in play store, even store version is greater than local version

**Comment by psdike** [comment]
Might be issue at your code part send  your perfomed code for new version
This plugin is quite easy

**Comment by timtraversy** [comment]
Could I ask what your package name is? And what are the exact version strings for the local and play versions?

**Comment by psdike** [comment]
> Could I ask what your package name is? And what are the exact version strings for the local and play versions?

Here is my package. I have set my condition for update with available local variables now my problem is solved!!

https://play.google.com/store/apps/details?id=in.psdike.mpscallpapersandanswers

**Comment by timtraversy** [comment]
Thanks! But I was asking @engajerest so I can solve his issue.

**Comment by timtraversy** [comment]
Let me know if you can provide more information about this.
