### ISSUE TITLE
Failed host lookup: 'play.google.com'

### ISSUE THREAD

**Issue by StanislawNagorski** [timtraversy/new_version#57]
Hi!
Thx for all the work You did with plugin! 
However I struggle to get it going...

I get:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SocketException: Failed host lookup: 'play.google.com' (OS Error: No address associated with hostname, errno = 7)`
while traing to invoke: showAlertIfNecessary.
My app have all Internet rights.
App is published on play store, and I debug it by implamanting code, and descreesing version lvl.

Any ideas?
Thx a lot for any help

**Comment by timtraversy** [comment]
This looks like it is an internet connection issue, I don't think this is a plugin bug.

Are you on a physical device or emulator? And can you access normal web pages in the browser on your device?

**Comment by StanislawNagorski** [comment]
Yes You were right it was my emulator.
It worked fine on device, and on emulator after I reinstal it. Thx!!

**Comment by mrruby** [comment]
I have the same error on the real Android device
