### ISSUE TITLE
Possible to add a stream

### ISSUE THREAD

**Issue by sohaibnoman** [timtraversy/new_version#63]
Hi, I see that the only option of receiving the App Store version data is through a Future. It might be a good reason for why that is, but in case I want to force the user to update, I would need the information about a newer version to come through asap. So the rebuilds and I can tell the user to update before he does anything crazy, is there a possibility to add a stream as well, that would send data when a newer version is available?

**Comment by timtraversy** [comment]
That's an interesting idea, but I don't know how it would be accomplished.

The iOS lookup API doesn't provide the ability to register webhooks, so there is no way to automatically notify an app that there is an update. The only way to "stream" that data would be to poll the API at intervals. 

You can already do that by just calling `getVersionStatus` on a Timer, or calling it every time the user navigates home, for example.

**Comment by sohaibnoman** [comment]
Ah I see, would have been nice to only fetch data when necessary, but if thats not possible at the moment I will try out the timer or something similar. Thanks for the answer!
