### ISSUE TITLE
Version updates should always be prompted only when there is an update

### ISSUE THREAD

**Issue by myConsciousness** [timtraversy/new_version#65]
Hi great developer!

I like this package very much and have already used it in several apps.

However, the default for this package is to explicitly check the status to see if an update is available. For example, in the following case.

```dart
   final newVersion =
        NewVersion(androidId: FlavorConfig.instance.variables['androidId']);
    final status = await newVersion.getVersionStatus();

   // ↓ This
    if (status!.canUpdate) {
      newVersion.showUpdateDialog(
        context: context,
        versionStatus: status,
        dialogTitle: 'New Version Is Available!',
        updateButtonText: 'Update Right Now',
        dismissButtonText: 'Skip',
      );
    }
```

I didn't know about the canUpdate method when I first started using this package, and I thought that the package was doing this internally. And what happened was that I got this dialog even in the same case as the current version.

Are there any design circumstances that would require this to be done this way? I imagine that updates may remove internal processing from the app, but the version will always go up, and I don't see the benefit of using canUpdate to determine when to implement using this package.

Anyway thanks for the amazing development!

**Comment by timtraversy** [comment]
Hello! So, what would you like the implementation to look like? `showUpdateDialog` only shows a dialog if an update is available?

**Comment by timtraversy** [comment]
Hm - there's already a function `showAlertIfNecessary` that will automatically show a dialog if an update is available. `showUpdateDialog` is meant to allow greater customization, including deciding if/when to show a dialog. My opinion is the API is better the way it is now - plus it would be a breaking change.

**Comment by myConsciousness** [comment]
Hi @timtraversy !

Sorry, I forgot about this issue for a while.

Please forget about this issue as the above reply indicates that a solution to what I thought was the problem is available.

Thanks for your contribution! :)
