### ISSUE TITLE
Shows update available, when it isn't

### ISSUE THREAD

**Issue by bermanapps** [timtraversy/new_version#78]
Hi,
I using flutter.
Currently version In store is 1.1.9, and I'm running 1.2.0. And it still tells me to update.

Here is some code:

  newVersion.getVersionStatus().then((status) {

        print('status.canUpdate: ${status.canUpdate}');
        print('status.localVersion: ${status.localVersion}');
        print('status.storeVersion: ${status.storeVersion}');
        print('status.appStoreLink: ${status.appStoreLink}');

        GlobalCall.openUpdate = false;
        newVersion.showAlertIfNecessary();
      });
    }

Here is the log:

I/flutter ( 5929): status.canUpdate: true
I/flutter ( 5929): status.localVersion: 1.2.0
I/flutter ( 5929): status.storeVersion: 1.1.9

**Comment by bermanapps** [comment]
I see this is address below. Sorry for the inconvience, you can delete this.

**Comment by vxern** [comment]
Pull request #77 fixes this issue.

**Comment by timtraversy** [comment]
Thanks, closing as duplicate of #54
