### ISSUE TITLE
Provide an optional call back for Update Action button.

### ISSUE THREAD

**Issue by Ramkrishna-egov** [timtraversy/new_version#79]
User might need to do some additional functional calls , before navigating to playstore, So its better to provide an optional update action button like the dismiss action button @GoltVik @SachinGanesh It is just an additional feature which will be helpful to us.

**Comment by timtraversy** [comment]
I've added what I consider to be common customizations to the `showUpdateDialog` method. For greater customization, you should call `getVersionStatus`, and then display your own AlertDialog.

Thanks for raising the issue, but I don't want the plugin to become bloated.
