### ISSUE TITLE
How should we use this package in unit tests?

### ISSUE THREAD

**Issue by sebastianbuechler** [timtraversy/new_version#82]
I wanted to test my method where I use this plugin's `getVersionStatus` method. However, it will always throw the `debugPrint` message since the unit tests run on a desktop:
```dart
  Future<VersionStatus?> getVersionStatus() async {
    PackageInfo packageInfo = await PackageInfo.fromPlatform();
    if (Platform.isIOS) {
      return _getiOSStoreVersion(packageInfo);
    } else if (Platform.isAndroid) {
      return _getAndroidStoreVersion(packageInfo);
    } else {
      debugPrint(
          'The target platform "${Platform.operatingSystem}" is not yet supported by this package.');
    }
  }
```

Do you already have a solution for that? 

If not: Could there be an adjustment so that we can set optional the wanted platform on the creation of a new `NewVersion` and check if this is set when calling`getVersionStatus` and use it instead of the "real" platform?

**Comment by timtraversy** [comment]
Thanks, something like this is implemented in #75, I just need to merge it in.
