### ISSUE TITLE
can't find app store id

### ISSUE THREAD

**Issue by jormae** [timtraversy/new_version#87]
The codes return flutter: Can't find an app in the App Store with the id: com.maheedeen.xxx as well as play store.
Any solutions for the problems?

**Comment by timtraversy** [comment]
Yeah the API is returning an empty array for that bundle ID. Are you sure you've published this app in the app store under that ID?

**Comment by jormae** [comment]
> Yeah the API is returning an empty array for that bundle ID. Are you sure you've published this app in the app store under that ID?

Sure, my app is ready for sale for more than a month.

**Comment by timtraversy** [comment]
Is it only available outside the US? You may have to set `iOSAppStoreCountry`

**Comment by jormae** [comment]
> Is it only available outside the US? You may have to set `iOSAppStoreCountry`

Yeah, I just add iOSAppStoreCountry: 'TH', but it still displays the same error.

**Comment by timtraversy** [comment]
Hm I'm not sure what else to try. If `https://itunes.apple.com/lookup?bundleId=com.maheedeen.xxx&country=TH` doesn't return results, the plugin can't do much else. I would just make sure that's the correct ID.
It's hard for me to validate because I can't search the Thai app store.

**Comment by jormae** [comment]
> Hm I'm not sure what else to try. If `https://itunes.apple.com/lookup?bundleId=com.maheedeen.xxx&country=TH` doesn't return results, the plugin can't do much else. I would just make sure that's the correct ID. It's hard for me to validate because I can't search the Thai app store.

Sorry, my app id is com.example.iteach-pro

**Comment by timtraversy** [comment]
Ok that ID does return the correct result, so it should work.

**Comment by jormae** [comment]
> > Hm I'm not sure what else to try. If `https://itunes.apple.com/lookup?bundleId=com.maheedeen.xxx&country=TH` doesn't return results, the plugin can't do much else. I would just make sure that's the correct ID. It's hard for me to validate because I can't search the Thai app store.
> 
> Sorry, my app id is com.example.iteach-pro

> Ok that ID does return the correct result, so it should work.
Yes, it works now. But for android it still errors

**Comment by jormae** [comment]
> Ok that ID does return the correct result, so it should work.
It works both in iOS and android, thanks

**Comment by sebastianbuechler** [comment]
@timtraversy We had some confusing about the term `iOSId` in the docs. Isn't it the bundle id? Maybe add some examples of famous apps in the docs for clarity. We used for the app store app id provided by Apple. For example Revolut has this id for their mobile app id932493382 (https://apps.apple.com/us/app/revolut/id932493382).

**Comment by timtraversy** [comment]
If you want to discuss a possible change it would be best to open a new ticket. But yes it is the bundle ID.
