### ISSUE TITLE
Unhandled Exception: No MaterialLocalizations found.

### ISSUE THREAD

**Issue by editorvidinli** [timtraversy/new_version#88]
Tested on 0.2 and 0.3 version. on both error raised. 
I use GetMaterialApp as my top level app, but rest of app works normal. 
it shows exception in log and app can continue, but  new version warning cannot be displayed. 

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: No MaterialLocalizations found.
MyApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
The material library uses Localizations to generate messages, labels, and abbreviations.
To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
The specific widget that could not find a MaterialLocalizations ancestor was:
  MyApp
The ancestors of this widget were:
  [root]
#0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:76:7)
#1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:96:4)
#2      showDialog (package:flutter/src/material/dialog.dart:1032:10)
#3      NewVersion.showUpdateDialog (package:new_version/new_version.dart:233:5)
#4      NewVersion.showAlertIfNecessary (package:new_version/new_vers<…>
```

**Comment by timtraversy** [comment]
Hm I'm not familiar with the library that contains `GetMaterialApp`. I would consult their documentation. 

This plugin assumes you've nested the app in a `MaterialApp` widget, although I'm realizing that isn't explicitly stated anywhere.

There is some advice in the error message:
```

MyApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
The material library uses Localizations to generate messages, labels, and abbreviations.
To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
```

But if none of that helps, you will likely have to display your own custom alert.

**Comment by editorvidinli** [comment]
The first suggestion is unusable for me since I use GetMaterialApp and I can't do without it.

About "add a Localization widget with a MaterialLocalizations delegate": I'm already using Localization. I don't know what else should I do?

Third suggestion: "display your own custom alert." : How can I do that ?
Thank you.

**Comment by timtraversy** [comment]
```
final status = await newVersion.getVersionStatus();
showDialog(
      // Your custom dialog here
);
```

**Comment by timtraversy** [comment]
And by consult their documentation, I mean you can do a search in the `getx` repository for issues that seem similar to yours: https://github.com/jonataslaw/getx/issues?q=MaterialLocalizations

**Comment by gourav6m17** [comment]
@editorvidinli  
You can try the following:
`  WidgetsBinding.instance.addPostFrameCallback((_) async {  // add this thing before the dialog
    newVersion.showAlertIfNecessary(context: context);});
`
