### ISSUE TITLE
Android: cannot parse local version when using versionNameSuffix

### ISSUE THREAD

**Issue by mauriziopinotti** [timtraversy/new_version#89]
Hi,

I am using `versionNameSuffix` as follows in Android's `build.gradle`:

```groovy
    flavorDimensions "environment"
    productFlavors {
        local {
            dimension "environment"
            versionNameSuffix "-local"
        }
        dev {
            dimension "environment"
            versionNameSuffix "-dev"
        }
        prod {
            dimension "environment"
        }
    }
```

So, PacakgeInfo says my app version is `8.1.8-local` and this causes this plugin to fail parsing:

```
Invalid radix-10 number (at character 1)
8-local
^
```

I'd suggest passing versionName thru a regex before parsing it: see PR https://github.com/timtraversy/new_version/pull/90

**Comment by mauriziopinotti** [comment]
PR created: https://github.com/timtraversy/new_version/pull/90

**Comment by FCE-tc** [comment]
Was about to post the exact same issue. Thanks Mauriziopinotti
