### ISSUE TITLE
iOSAppStoreCountry parameter query

### ISSUE THREAD

**Issue by Samkit02** [timtraversy/new_version#95]
i have a query if my ios app is available in multiple countries including USA, INDIA, UAE and other countries what should i write in the iOSAppStoreCountry ??

please suggest..

i want to add this plugin into my app that i am planning to publish it before or on 20th March 2022 and my app will be avaiable in every country and mostly in ARAB countries.

please reply as soon as possible.

**Comment by timtraversy** [comment]
By default, the iTunes API will search the US App Store - so if it exists in there you can leave that parameter blank. You only need to set it if your app is *only* available outside the US Store.

**Comment by Samkit02** [comment]
> By default, the iTunes API will search the US App Store - so if it exists in there you can leave that parameter blank. You only need to set it if your app is *only* available outside the US Store.

That is why i am asking you i have my app in multiple countries so for that what can i do ???

**Comment by Samkit02** [comment]
> As I said, you can leave the parameter blank.
> 
> Are you pushing different versions to different countries?

If i leave the parameter blank it show update dialog in ios 

No i am not pushing different versions to different countries

Same release will be released everywhere

**Comment by timtraversy** [comment]
> If i leave the parameter blank it show update dialog in ios
Is this a question? Or is this the behavior you are seeing.

**Comment by Samkit02** [comment]
> > If i leave the parameter blank it show update dialog in ios
> 
> Is this a question? Or is this the behavior you are seeing.

Both

**Comment by timtraversy** [comment]
Could you post your:
1. Observed behavior
2. Expected behavior
3. The local and store versions of your app
